---
- name: Enabling Docker-CE repository
  get_url:
    url: "{{ docker_ce_url }}"
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644

- name: Install YUM dependencies
  yum:
    name: "{{ dependencies.pkg }}"
    update_cache: yes

- name: Install Python dependencies
  pip:
    name: "{{ dependencies.pip }}"

- name: Create Docker compose directory
  file:
    path: "{{ rabbitmq_compose_dir }}"
    state: directory

- name: Create RabbitMQ data directory
  file:
    path: "{{ rabbitmq_compose_dir }}/data"
    state: directory

- name: Template Docker compose and RabbitMQ configs
  template:
    src: "{{ item.src }}"
    dest: "{{ rabbitmq_compose_dir }}/{{ item.dst }}"
    mode: 0644
  with_items:
    - { src: docker-compose.yml.j2, dst: docker-compose.yml }
    - { src: rabbitmq.config.j2, dst: rabbitmq.config }
    - { src: definitions.json.j2, dst: definitions.json }
  notify: Enable RabbitMQ

- name: Starting Docker services
  systemd:
    name: docker.service
    state: started
    enabled: yes

- name: Create Docker network
  docker_network:
    name: "{{ docker_network_name }}"
