---
- name: Create Docker network
  docker_network:
    name: "{{ docker_network_name }}"

- name: Start all AWX containers
  docker_service:
    project_name: "awx"
    project_src: "{{ awx_compose_dir }}/"
