---
- name: Create Docker network
  docker_network:
    name: "{{ docker_network_name }}"

- name: Start Webhook container
  docker_service:
    project_name: "webhook"
    project_src: "{{ webhook_compose_dir }}/"